env:
  TERM: alacritty
font:
  size: 14.0
key_bindings:
  - { key: Semicolon,    mods: Command|Shift,     action: IncreaseFontSize               }
  - { key: Minus,        mods: Command|Shift,     action: DecreaseFontSize               }
window:
  opacity: 0.8
import:
  - ~/.config/alacritty/dracula.yml
